import { ApplicantInfo } from 'features/build-application/types'

export const APPLICANT_BASIC_INFO: ApplicantInfo[] = [
  {
    ko: '성별',
    en: 'Gender',
    icon: 'icon/gender-line',
    key: 'gender',
    is_required: true,
    is_canview: true,
  },
  {
    ko: '생년월일',
    en: 'Birthday',
    icon: 'icon/birth-solid',
    key: 'birthday',
    is_required: false,
    is_canview: true,
  },
  {
    ko: '지원자 사진',
    en: 'Profile',
    icon: 'icon/image-line',
    key: 'profile',
    is_required: false,
    is_canview: true,
  },
  {
    ko: '국적',
    en: 'Nationality',
    icon: 'icon/nationality-line',
    key: 'nationality',
    is_required: false,
    is_canview: true,
  },
  {
    ko: '거주지',
    en: 'Address',
    icon: 'icon/map-line',
    key: 'address',
    is_required: false,
    is_canview: true,
  },
  {
    ko: '장애 여부',
    en: 'Disabled',
    icon: 'icon/wheel-chair-line',
    key: 'disabled',
    is_required: true,
    is_canview: true,
  },
  {
    ko: '보훈 여부',
    en: 'Veteran Benefit',
    icon: 'icon/rewarding-patriotism-line',
    key: 'veteran_benefit',
    is_required: true,
    is_canview: true,
  },
]

export const APPLICANT_EDUCATION_INFO: ApplicantInfo[] = [
  {
    ko: '학력',
    en: 'Education',
    icon: 'icon/education-line',
    key: 'educations',
    is_required: false,
    is_canview: true,
    is_note: false,
  },
]

export const APPLICANT_EXPERIENCE_INFO: ApplicantInfo[] = [
  {
    ko: '경력',
    en: 'Career',
    icon: 'icon/career-line',
    key: 'careers',
    is_required: true,
    is_canview: true,
    is_note: false,
  },
  {
    ko: '대외 활동',
    en: 'Activity',
    icon: 'icon/activity-line',
    key: 'activities',
    is_required: true,
    is_canview: true,
    is_note: false,
  },
  {
    ko: '병역 사항',
    en: 'Military',
    icon: 'icon/military-line',
    key: 'military',
    is_required: true,
    is_canview: true,
  },
]

export const APPLICANT_DOCUMENT_INFO: ApplicantInfo[] = [
  {
    ko: '어학',
    en: 'Language',
    icon: 'icon/language-line',
    key: 'languages',
    is_required: true,
    is_canview: true,
    is_note: false,
  },
  {
    ko: '자격증 또는 면허',
    en: 'License',
    icon: 'icon/license-line',
    key: 'licenses',
    is_required: true,
    is_canview: true,
    is_note: false,
  },
  {
    ko: '수상',
    en: 'Awards',
    icon: 'icon/award-line',
    key: 'awards',
    is_required: true,
    is_canview: true,
    is_note: false,
  },
  {
    ko: '이력서',
    en: 'Documents',
    icon: 'icon/document-line',
    key: 'resume',
    is_required: true,
    is_canview: true,
    is_note: false,
  },
  {
    ko: '추가 서류',
    en: 'Add Documents',
    icon: 'icon/add-resources-line',
    desc: '추가 서류 항목 추가 (다중 추가 가능)',
    key: 'documents',
    is_required: false,
    is_canview: true,
    is_note: false,
    is_title: true,
    is_multiple: true,
  },
  {
    ko: '사전 질문',
    en: 'Pre Question',
    icon: 'icon/Q&A-line',
    desc: '사전 질문 항목 추가 (다중 추가 가능)',
    key: 'pre_questions',
    is_required: false,
    is_canview: true,
    is_note: false,
    is_question: true,
    is_multiple: true,
  },
]
