export const folders = [
  {
    folder_id: '0',
    folder_name: '폴더0',
    postings: [
      {
        id: '0-0',
        title: '공고0',
        isActive: true,
        isClose: true,
        isMember: true,
        sort: 0,
      },
      {
        id: '0-1',
        title: '공고1',
        isActive: true,
        isClose: true,
        isMember: false,
        sort: 1,
      },
      {
        id: '0-1',
        title: '공고1',
        isActive: true,
        isClose: false,
        isMember: false,
        sort: 2,
      },
      {
        id: '0-1',
        title: '공고1',
        isActive: false,
        isClose: false,
        isMember: false,
        sort: 3,
      },
    ],
  },
  {
    folder_id: '1',
    folder_name: '폴더1',
    postings: [
      {
        id: '0-0',
        title: '공고0',
        isActive: false,
        isClose: true,
        isMember: true,
        sort: 0,
      },
      {
        id: '0-1',
        title: '공고1',
        isActive: false,
        isClose: true,
        isMember: true,
        sort: 1,
      },
      {
        id: '0-1',
        title: '공고1',
        isActive: false,
        isClose: false,
        isMember: true,
        sort: 2,
      },
      {
        id: '0-1',
        title: '공고1',
        isActive: false,
        isClose: false,
        isMember: false,
        sort: 3,
      },
    ],
  },
]
