export const REFERER: Record<string, string> = {
  'blog.naver.com': '네이버',
  'www.rocketpunch.com': '로켓펀치',
  'www.jobkorea.co.kr': '잡코리아',
  'www.beginmate.com': '비긴메이트',
  'www.heding.co.kr': '헤딩',
  'www.jobflex.com': '잡플렉스',
  'www.incruit.com': '인크루트',
  'careerly.co.kr': '커리어리',
  'impact.career': '임펙트커리어',
  'www.albamon.com': '알바몬',
  'www.alba.co.kr': '알바천국',
  'www.jumpit.co.kr': '점핏',
  'linkstarter.co': '링크스타터',
  'jasoseol.com': '자소설닷컴',
  'www.superookie.com': '슈퍼루키',
  'www.theteams.kr': '더팀스',
  'www.gamejob.co.kr': '게임잡',
  'cafe.naver.com': '네이버카페',
  'careers.kakao.com': '카카오영입',
  'kr.linkedin.com': '링크드인',
  'www.saramin.co.kr': '사람인',
}
