export const PAGE = {
  POWERED_BY: 'https://www.steadhr.com/',
  HOME: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  CREATE_EMAIL: '/create-email',
  CHANGE_PASSWORD: '/change-password',
  TEAMS: '/teams',
  MEMBERS: '/members',
  APPLICANTS: '/applicants',
  CALENDAR: '/calendar',
  MAIL: '/mail',
  MAIL_INBOX: '/mail/in',
  MAIL_SENT: '/mail/sent',
  MAIL_TRASH: '/mail/trash',
  POSTING_LOCKER: '/posting-locker',
  POSTINGS: (id: number) => `/postings/${id}`,
  CREATE_POSTING: '/create-posting',
  EDIT_POSTING: (id: number) => `/edit-posting?id=${id}`,
  PREVIEW_RECRUIT: '/recruit/preview',
  POSTINGS_DETAIL: (id: number | string) => `/postings/${id}`,
  RECRUIT: (url: string, id: number) => `/recruit/${url}/${id}`,
  RECRUIT_APPLY: (enterpriseName: string, id: string) => `/recruit/${enterpriseName}/${id}/apply`,
  NOTION_URL: 'https://stead-guide.readme.io/docs',
  INQUIRY_PASSWORD: '/inquiry-password',
  TERMS_OF_SERVICE: '/terms-of-service',
  PRIVACY_POLICY: '/privacy-policy',
  EXPIRE: '/expire',
  /*setting*/
  SETTINGS_ACCOUNT: '/settings/account',
  SETTINGS_APPS: '/settings/apps',
  SETTINGS_ENTERPRISE: '/settings/enterprise',
  SETTINGS_MEMBER: '/settings/member',
  SETTINGS_POSTING: '/settings/posting',
  SETTINGS_TEMPLATE: '/settings/template',
  SETTINGS_PAYMENT: '/settings/payment',
  SETTINGS_PAYMENT_HISTORY: '/settings/payment-history',
  PLAN_EXPIRED: '/plan-expired',
  BUILD_APPLICATION: (id: number | string) => `/build-application/${id}`,
  PREVIEW_BUILD_APPLICATION: '/build-application/preview',
  EDIT_BUILD_APPLICATION: (id: number | string) => `/build-application/${id}?edit=true`,
  CREATE_APPLICATION_TEMPLATE: '/create-application-template',
  EDIT_APPLICATION_TEMPLATE: (id: number) => `/edit-application-template/${id}`,

  /*onboarding*/
  ONBOARDING: '/onboarding',
  ONBOARDING_REPORTS: '/onboarding/reports',
  SCENARIOS: '/scenarios',
  CREATE_SCENARIO: '/create-scenario',
}
